name = "LeanStuff"
version = "0.1.0"
defaultTargets = ["leanstuff"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

[[lean_lib]]
name = "LeanStuff"

[[lean_exe]]
name = "leanstuff"
root = "Main"
